#include "Support/APFloat.cpp"
#undef DEBUG_TYPE
#include "Support/APInt.cpp"
#undef DEBUG_TYPE
#include "Support/CommandLine.cpp"
#undef DEBUG_TYPE
#include "Support/ConvertUTF.cpp"
#undef DEBUG_TYPE
#include "Support/ConvertUTFWrapper.cpp"
#undef DEBUG_TYPE
#include "Support/CrashRecoveryContext.cpp"
#undef DEBUG_TYPE
#include "Support/Debug.cpp"
#undef DEBUG_TYPE
#include "Support/DebugCounter.cpp"
#undef DEBUG_TYPE
#include "Support/DebugOptions.h"
#undef DEBUG_TYPE
#include "Support/Errno.cpp"
#undef DEBUG_TYPE
#include "Support/Error.cpp"
#undef DEBUG_TYPE
#include "Support/ErrorHandling.cpp"
#undef DEBUG_TYPE
#include "Support/ExtensibleRTTI.cpp"
#undef DEBUG_TYPE
#include "Support/FormatVariadic.cpp"
#undef DEBUG_TYPE
#include "Support/GraphWriter.cpp"
#undef DEBUG_TYPE
#include "Support/Locale.cpp"
#undef DEBUG_TYPE
#include "Support/MD5.cpp"
#undef DEBUG_TYPE

#undef F
#undef G
#undef H
#undef I
#undef STEP
#undef SET
#undef GET
#include "Support/ManagedStatic.cpp"
#undef DEBUG_TYPE
#include "Support/MemAlloc.cpp"
#undef DEBUG_TYPE
#include "Support/MemoryBuffer.cpp"
#undef DEBUG_TYPE
#include "Support/NativeFormatting.cpp"
#undef DEBUG_TYPE
#include "Support/Path.cpp"
#undef DEBUG_TYPE
#include "Support/Process.cpp"
#undef DEBUG_TYPE
#include "Support/Program.cpp"
#undef DEBUG_TYPE
#include "Support/RandomNumberGenerator.cpp"
#undef DEBUG_TYPE
#include "Support/Signals.cpp"
#undef DEBUG_TYPE
#include "Support/Signposts.cpp"
#undef DEBUG_TYPE
#include "Support/SmallPtrSet.cpp"
#undef DEBUG_TYPE
#include "Support/SmallVector.cpp"
#undef DEBUG_TYPE
#include "Support/SourceMgr.cpp"
#undef DEBUG_TYPE
#include "Support/Statistic.cpp"
#undef DEBUG_TYPE
#include "Support/StringExtras.cpp"
#undef DEBUG_TYPE
#include "Support/StringMap.cpp"
#undef DEBUG_TYPE
#include "Support/StringRef.cpp"
#undef DEBUG_TYPE
#include "Support/StringSaver.cpp"
#undef DEBUG_TYPE
#include "Support/Threading.cpp"
#undef DEBUG_TYPE
#include "Support/Timer.cpp"
#undef DEBUG_TYPE
#include "Support/Twine.cpp"
#undef DEBUG_TYPE
#include "Support/TypeSize.cpp"
#undef DEBUG_TYPE
#include "Support/Unicode.cpp"
#undef DEBUG_TYPE
#include "Support/Unix/Unix.h"
#undef DEBUG_TYPE
#include "Support/VirtualFileSystem.cpp"
#undef DEBUG_TYPE
#include "Support/WithColor.cpp"
#undef DEBUG_TYPE
#include "Support/YAMLParser.cpp"
#undef DEBUG_TYPE
#include "Support/circular_raw_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/raw_os_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/raw_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/xxhash.cpp"
#undef DEBUG_TYPE
