#include "Support/ABIBreak.cpp"
#undef DEBUG_TYPE
#include "Support/AMDGPUMetadata.cpp"
#undef DEBUG_TYPE
#include "Support/APFixedPoint.cpp"
#undef DEBUG_TYPE
#include "Support/APFloat.cpp"
#undef DEBUG_TYPE
#include "Support/APInt.cpp"
#undef DEBUG_TYPE
#include "Support/APSInt.cpp"
#undef DEBUG_TYPE
#include "Support/ARMWinEH.cpp"
#undef DEBUG_TYPE
#include "Support/Allocator.cpp"
#undef DEBUG_TYPE
#include "Support/Atomic.cpp"
#undef DEBUG_TYPE
#include "Support/AutoConvert.cpp"
#undef DEBUG_TYPE
#include "Support/BalancedPartitioning.cpp"
#undef DEBUG_TYPE
#include "Support/Base64.cpp"
#undef DEBUG_TYPE
#include "Support/BinaryStreamError.cpp"
#undef DEBUG_TYPE
#include "Support/BinaryStreamReader.cpp"
#undef DEBUG_TYPE
#include "Support/BinaryStreamRef.cpp"
#undef DEBUG_TYPE
#include "Support/BinaryStreamWriter.cpp"
#undef DEBUG_TYPE
#include "Support/BlockFrequency.cpp"
#undef DEBUG_TYPE
#include "Support/BranchProbability.cpp"
#undef DEBUG_TYPE
#include "Support/BuryPointer.cpp"
#undef DEBUG_TYPE
#include "Support/COM.cpp"
#undef DEBUG_TYPE
#include "Support/CRC.cpp"
#undef DEBUG_TYPE
#include "Support/CachePruning.cpp"
#undef DEBUG_TYPE
#include "Support/Caching.cpp"
#undef DEBUG_TYPE
#include "Support/Chrono.cpp"
#undef DEBUG_TYPE
#include "Support/CodeGenCoverage.cpp"
#undef DEBUG_TYPE
#include "Support/CommandLine.cpp"
#undef DEBUG_TYPE
#include "Support/Compression.cpp"
#undef DEBUG_TYPE
#include "Support/ConvertEBCDIC.cpp"
#undef DEBUG_TYPE
#include "Support/ConvertUTF.cpp"
#undef DEBUG_TYPE
#include "Support/ConvertUTFWrapper.cpp"
#undef DEBUG_TYPE
#include "Support/CrashRecoveryContext.cpp"
#undef DEBUG_TYPE
#include "Support/DAGDeltaAlgorithm.cpp"
#undef DEBUG_TYPE
#include "Support/DJB.cpp"
#undef DEBUG_TYPE
#include "Support/DataExtractor.cpp"
#undef DEBUG_TYPE
#include "Support/Debug.cpp"
#undef DEBUG_TYPE
#include "Support/DebugCounter.cpp"
#undef DEBUG_TYPE
#include "Support/DeltaAlgorithm.cpp"
#undef DEBUG_TYPE
#include "Support/DeltaTree.cpp"
#undef DEBUG_TYPE
#include "Support/DivisionByConstantInfo.cpp"
#undef DEBUG_TYPE
#include "Support/DynamicAPInt.cpp"
#undef DEBUG_TYPE
#include "Support/DynamicLibrary.cpp"
#undef DEBUG_TYPE
#include "Support/Errno.cpp"
#undef DEBUG_TYPE
#include "Support/Error.cpp"
#undef DEBUG_TYPE
#include "Support/ErrorHandling.cpp"
#undef DEBUG_TYPE
#include "Support/ExponentialBackoff.cpp"
#undef DEBUG_TYPE
#include "Support/ExtensibleRTTI.cpp"
#undef DEBUG_TYPE
#include "Support/FileCollector.cpp"
#undef DEBUG_TYPE
#include "Support/FileOutputBuffer.cpp"
#undef DEBUG_TYPE
#include "Support/FileUtilities.cpp"
#undef DEBUG_TYPE
#include "Support/FloatingPointMode.cpp"
#undef DEBUG_TYPE
#include "Support/FoldingSet.cpp"
#undef DEBUG_TYPE
#include "Support/FormatVariadic.cpp"
#undef DEBUG_TYPE
#include "Support/FormattedStream.cpp"
#undef DEBUG_TYPE
#include "Support/GlobPattern.cpp"
#undef DEBUG_TYPE
#include "Support/GraphWriter.cpp"
#undef DEBUG_TYPE
#include "Support/InitLLVM.cpp"
#undef DEBUG_TYPE
#include "Support/InstructionCost.cpp"
#undef DEBUG_TYPE
#include "Support/IntEqClasses.cpp"
#undef DEBUG_TYPE
#include "Support/IntervalMap.cpp"
#undef DEBUG_TYPE
#include "Support/JSON.cpp"
#undef DEBUG_TYPE
#include "Support/KnownBits.cpp"
#undef DEBUG_TYPE
#include "Support/LEB128.cpp"
#undef DEBUG_TYPE
#include "Support/LineIterator.cpp"
#undef DEBUG_TYPE
#include "Support/Locale.cpp"
#undef DEBUG_TYPE
#include "Support/LockFileManager.cpp"
#undef DEBUG_TYPE
#include "Support/MD5.cpp"
#undef DEBUG_TYPE
#include "Support/ManagedStatic.cpp"
#undef DEBUG_TYPE
#include "Support/MathExtras.cpp"
#undef DEBUG_TYPE
#include "Support/MemAlloc.cpp"
#undef DEBUG_TYPE
#include "Support/Memory.cpp"
#undef DEBUG_TYPE
#include "Support/MemoryBuffer.cpp"
#undef DEBUG_TYPE
#include "Support/MemoryBufferRef.cpp"
#undef DEBUG_TYPE
#include "Support/ModRef.cpp"
#undef DEBUG_TYPE
#include "Support/NativeFormatting.cpp"
#undef DEBUG_TYPE
#include "Support/OptimizedStructLayout.cpp"
#undef DEBUG_TYPE
#include "Support/OptionStrCmp.cpp"
#undef DEBUG_TYPE
#include "Support/Optional.cpp"
#undef DEBUG_TYPE
#include "Support/PGOOptions.cpp"
#undef DEBUG_TYPE
#include "Support/Parallel.cpp"
#undef DEBUG_TYPE
#include "Support/Path.cpp"
#undef DEBUG_TYPE
#include "Support/PluginLoader.cpp"
#undef DEBUG_TYPE
#include "Support/PrettyStackTrace.cpp"
#undef DEBUG_TYPE
#include "Support/Process.cpp"
#undef DEBUG_TYPE
#include "Support/Program.cpp"
#undef DEBUG_TYPE
#include "Support/RISCVISAUtils.cpp"
#undef DEBUG_TYPE
#include "Support/RWMutex.cpp"
#undef DEBUG_TYPE
#include "Support/RandomNumberGenerator.cpp"
#undef DEBUG_TYPE
#include "Support/Regex.cpp"
#undef DEBUG_TYPE
#include "Support/SHA1.cpp"
#undef DEBUG_TYPE
#include "Support/SHA256.cpp"
#undef DEBUG_TYPE
#include "Support/ScaledNumber.cpp"
#undef DEBUG_TYPE
#include "Support/ScopedPrinter.cpp"
#undef DEBUG_TYPE
#include "Support/Signals.cpp"
#undef DEBUG_TYPE
#include "Support/Signposts.cpp"
#undef DEBUG_TYPE
#include "Support/SipHash.cpp"
#undef DEBUG_TYPE
#include "Support/SlowDynamicAPInt.cpp"
#undef DEBUG_TYPE
#include "Support/SmallPtrSet.cpp"
#undef DEBUG_TYPE
#include "Support/SmallVector.cpp"
#undef DEBUG_TYPE
#include "Support/SourceMgr.cpp"
#undef DEBUG_TYPE
#include "Support/SpecialCaseList.cpp"
#undef DEBUG_TYPE
#include "Support/Statistic.cpp"
#undef DEBUG_TYPE
#include "Support/StringExtras.cpp"
#undef DEBUG_TYPE
#include "Support/StringMap.cpp"
#undef DEBUG_TYPE
#include "Support/StringRef.cpp"
#undef DEBUG_TYPE
#include "Support/StringSaver.cpp"
#undef DEBUG_TYPE
#include "Support/SuffixTree.cpp"
#undef DEBUG_TYPE
#include "Support/SuffixTreeNode.cpp"
#undef DEBUG_TYPE
#include "Support/SystemUtils.cpp"
#undef DEBUG_TYPE
#include "Support/TarWriter.cpp"
#undef DEBUG_TYPE
#include "Support/ThreadPool.cpp"
#undef DEBUG_TYPE
#include "Support/Threading.cpp"
#undef DEBUG_TYPE
#include "Support/TimeProfiler.cpp"
#undef DEBUG_TYPE
#include "Support/Timer.cpp"
#undef DEBUG_TYPE
#include "Support/ToolOutputFile.cpp"
#undef DEBUG_TYPE
#include "Support/TrieRawHashMap.cpp"
#undef DEBUG_TYPE
#include "Support/Twine.cpp"
#undef DEBUG_TYPE
#include "Support/TypeSize.cpp"
#undef DEBUG_TYPE
#include "Support/Unicode.cpp"
#undef DEBUG_TYPE
#include "Support/UnicodeCaseFold.cpp"
#undef DEBUG_TYPE
#include "Support/UnicodeNameToCodepoint.cpp"
#undef DEBUG_TYPE
#include "Support/UnicodeNameToCodepointGenerated.cpp"
#undef DEBUG_TYPE
#include "Support/Valgrind.cpp"
#undef DEBUG_TYPE
#include "Support/VersionTuple.cpp"
#undef DEBUG_TYPE
#include "Support/VirtualFileSystem.cpp"
#undef DEBUG_TYPE
#include "Support/Watchdog.cpp"
#undef DEBUG_TYPE
#include "Support/WithColor.cpp"
#undef DEBUG_TYPE
#include "Support/YAMLParser.cpp"
#undef DEBUG_TYPE
#include "Support/YAMLTraits.cpp"
#undef DEBUG_TYPE
#include "Support/Z3Solver.cpp"
#undef DEBUG_TYPE
#include "Support/circular_raw_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/raw_os_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/raw_ostream.cpp"
#undef DEBUG_TYPE
#include "Support/raw_socket_stream.cpp"
#undef DEBUG_TYPE
#include "Support/xxhash.cpp"
#undef DEBUG_TYPE
